### ISSUE TITLE
impressive and some doubts

### ISSUE THREAD

**Issue by denisdemaisbr** [dimkr/szl#12]
some doubts:
1- supports 16, 32 and 64-bit compilers?
2- support anothers c compilers, like microsoft c++, tcc, bcc or armcc ?
3- is endianess safe (little and big-endian cpus) ?
4- curated projects ?

thanks!

**Comment by dimkr** [comment]
1 - yes
2 - it should work with any gcc or clang compatible compiler
3 - yes
4 - didn't understand the question
