### ISSUE TITLE
Is portability a priority here?

### ISSUE THREAD

**Issue by ghost** [dimkr/szl#3]
Greetings,
I've been trying to compile szl under OpenBSD, and I got a compiler error, for some missing stuff (I don't remember what exactly) in the src/szl_exec.c file, so I figured out that it's signal.h is missing, and I included it, here is a patch:

```
diff --git a/src/szl_exec.c b/src/szl_exec.c
index 9b31806..7bc1ae7 100644
--- a/src/szl_exec.c
+++ b/src/szl_exec.c
@@ -22,6 +22,7 @@
  * THE SOFTWARE.
  */

+#include <signal.h>
 #include <stdlib.h>
 #include <unistd.h>
 #include <errno.h>
```

However, I kept getting issues about implicit declarations in other files 'szl_poll.c' and the issue is, sys/epoll.h is a linux header, and it's not portable, so including such a thing will harm portability and prevent me from running szl on openbsd, are you aware of that?

**Comment by dimkr** [comment]
Right now portability is not a priority. I do my best to make things as standard and portable as possible, unless there's a very useful proprietary Linux interface (such as `epoll`). Most of the code should be either BSD-compatible or trivial to port.

Thanks for the missing include.
