### ISSUE TITLE
szl_builtin.c:27:2: error: use of undeclared identifier 'n'

### ISSUE THREAD

**Issue by kainjow** [dimkr/szl#7]
Attempting a build on macOS Sierra, but I get this after running `make`:

```
szl_builtin.c:27:2: error: use of undeclared identifier 'n'
-n "obj", 
 ^
```

**Comment by kainjow** [comment]
I noticed in the output `make[1]: pkg-config: Command not found` but even after installing pig-config (via Homebrew) I still get the same error.

**Comment by ghost** [comment]
If you bothered reading other issues (this one specifically: https://github.com/dimkr/szl/issues/3), you will know that szl is not meant for Linux, unless your lovely mac osx provides a compat layer.

**Comment by dimkr** [comment]
@kainjow: right now, szl targets only Linux. I'm currently working on a CMake-based build system in the "cmake" branch, to make a future Windows easier. *BSD and OS X ports are a possibility, too.
